package com.liuy.dao.entry;

public class Goodproxy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodProxy.ip
     *
     * @mbg.generated Wed Mar 03 16:56:37 CST 2021
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodProxy.port
     *
     * @mbg.generated Wed Mar 03 16:56:37 CST 2021
     */
    private Integer port;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodProxy.ip
     *
     * @return the value of goodProxy.ip
     *
     * @mbg.generated Wed Mar 03 16:56:37 CST 2021
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodProxy.ip
     *
     * @param ip the value for goodProxy.ip
     *
     * @mbg.generated Wed Mar 03 16:56:37 CST 2021
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodProxy.port
     *
     * @return the value of goodProxy.port
     *
     * @mbg.generated Wed Mar 03 16:56:37 CST 2021
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodProxy.port
     *
     * @param port the value for goodProxy.port
     *
     * @mbg.generated Wed Mar 03 16:56:37 CST 2021
     */
    public void setPort(Integer port) {
        this.port = port;
    }
}