package com.liuy.dao.mapper;


import com.liuy.dao.entry.Bili;
import com.liuy.dao.entry.BiliExample;

public interface BiliMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bili
     *
     * @mbg.generated Fri Feb 26 11:22:07 CST 2021
     */
    long countByExample(BiliExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bili
     *
     * @mbg.generated Fri Feb 26 11:22:07 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bili
     *
     * @mbg.generated Fri Feb 26 11:22:07 CST 2021
     */
    int insert(Bili record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bili
     *
     * @mbg.generated Fri Feb 26 11:22:07 CST 2021
     */
    int insertSelective(Bili record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bili
     *
     * @mbg.generated Fri Feb 26 11:22:07 CST 2021
     */
    Bili selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bili
     *
     * @mbg.generated Fri Feb 26 11:22:07 CST 2021
     */
    int updateByPrimaryKeySelective(Bili record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bili
     *
     * @mbg.generated Fri Feb 26 11:22:07 CST 2021
     */
    int updateByPrimaryKey(Bili record);
}