package com.liuy.dao.mapper;

import com.liuy.dao.entry.Bili;
import com.liuy.dao.entry.BiliExample;

import java.util.List;

public interface BiliMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bili
     *
     * @mbg.generated Sat Mar 06 11:00:13 CST 2021
     */
    long countByExample(BiliExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bili
     *
     * @mbg.generated Sat Mar 06 11:00:13 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bili
     *
     * @mbg.generated Sat Mar 06 11:00:13 CST 2021
     */
    int insert(Bili record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bili
     *
     * @mbg.generated Sat Mar 06 11:00:13 CST 2021
     */
    int insertSelective(Bili record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bili
     *
     * @mbg.generated Sat Mar 06 11:00:13 CST 2021
     */
    Bili selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bili
     *
     * @mbg.generated Sat Mar 06 11:00:13 CST 2021
     */
    int updateByPrimaryKeySelective(Bili record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bili
     *
     * @mbg.generated Sat Mar 06 11:00:13 CST 2021
     */
    int updateByPrimaryKey(Bili record);

    List<Bili> getUserRandByLimit(int uid,int limit);
}