package com.liuy.dao.mapper;


import com.liuy.dao.entry.Bilibilistep;
import com.liuy.dao.entry.BilibilistepExample;

public interface BilibilistepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bilibiliStep
     *
     * @mbg.generated Fri Feb 19 15:09:54 CST 2021
     */
    long countByExample(BilibilistepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bilibiliStep
     *
     * @mbg.generated Fri Feb 19 15:09:54 CST 2021
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bilibiliStep
     *
     * @mbg.generated Fri Feb 19 15:09:54 CST 2021
     */
    int insert(Bilibilistep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bilibiliStep
     *
     * @mbg.generated Fri Feb 19 15:09:54 CST 2021
     */
    int insertSelective(Bilibilistep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bilibiliStep
     *
     * @mbg.generated Fri Feb 19 15:09:54 CST 2021
     */
    Bilibilistep selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bilibiliStep
     *
     * @mbg.generated Fri Feb 19 15:09:54 CST 2021
     */
    int updateByPrimaryKeySelective(Bilibilistep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bilibiliStep
     *
     * @mbg.generated Fri Feb 19 15:09:54 CST 2021
     */
    int updateByPrimaryKey(Bilibilistep record);
}