package com.liuy.dao.mapper;


import com.liuy.dao.entry.Goodproxy;
import com.liuy.dao.entry.GoodproxyExample;

public interface GoodproxyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodProxy
     *
     * @mbg.generated Wed Mar 03 16:56:37 CST 2021
     */
    long countByExample(GoodproxyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodProxy
     *
     * @mbg.generated Wed Mar 03 16:56:37 CST 2021
     */
    int deleteByPrimaryKey(String ip);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodProxy
     *
     * @mbg.generated Wed Mar 03 16:56:37 CST 2021
     */
    int insert(Goodproxy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodProxy
     *
     * @mbg.generated Wed Mar 03 16:56:37 CST 2021
     */
    int insertSelective(Goodproxy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodProxy
     *
     * @mbg.generated Wed Mar 03 16:56:37 CST 2021
     */
    Goodproxy selectByPrimaryKey(String ip);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodProxy
     *
     * @mbg.generated Wed Mar 03 16:56:37 CST 2021
     */
    int updateByPrimaryKeySelective(Goodproxy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodProxy
     *
     * @mbg.generated Wed Mar 03 16:56:37 CST 2021
     */
    int updateByPrimaryKey(Goodproxy record);
}