package com.myLogger.dao.entry;

public class Bilibili {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bilibili.mid
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    private Long mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bilibili.name
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bilibili.sex
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bilibili.rank
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    private String rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bilibili.face
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    private String face;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bilibili.birthday
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bilibili.description
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bilibili.article
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    private String article;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bilibili.attention
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    private String attention;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bilibili.fans
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    private Long fans;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bilibili.friend
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    private String friend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bilibili.sign
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    private String sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bilibili.vipType
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    private Integer viptype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bilibili.vipStatus
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    private Integer vipstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bilibili.archive_count
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    private Long archiveCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bilibili.article_count
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    private Long articleCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bilibili.follower
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    private Long follower;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bilibili.mid
     *
     * @return the value of bilibili.mid
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public Long getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bilibili.mid
     *
     * @param mid the value for bilibili.mid
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public void setMid(Long mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bilibili.name
     *
     * @return the value of bilibili.name
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bilibili.name
     *
     * @param name the value for bilibili.name
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bilibili.sex
     *
     * @return the value of bilibili.sex
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bilibili.sex
     *
     * @param sex the value for bilibili.sex
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bilibili.rank
     *
     * @return the value of bilibili.rank
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bilibili.rank
     *
     * @param rank the value for bilibili.rank
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public void setRank(String rank) {
        this.rank = rank == null ? null : rank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bilibili.face
     *
     * @return the value of bilibili.face
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public String getFace() {
        return face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bilibili.face
     *
     * @param face the value for bilibili.face
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public void setFace(String face) {
        this.face = face == null ? null : face.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bilibili.birthday
     *
     * @return the value of bilibili.birthday
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bilibili.birthday
     *
     * @param birthday the value for bilibili.birthday
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bilibili.description
     *
     * @return the value of bilibili.description
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bilibili.description
     *
     * @param description the value for bilibili.description
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bilibili.article
     *
     * @return the value of bilibili.article
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public String getArticle() {
        return article;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bilibili.article
     *
     * @param article the value for bilibili.article
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public void setArticle(String article) {
        this.article = article == null ? null : article.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bilibili.attention
     *
     * @return the value of bilibili.attention
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public String getAttention() {
        return attention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bilibili.attention
     *
     * @param attention the value for bilibili.attention
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public void setAttention(String attention) {
        this.attention = attention == null ? null : attention.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bilibili.fans
     *
     * @return the value of bilibili.fans
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public Long getFans() {
        return fans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bilibili.fans
     *
     * @param fans the value for bilibili.fans
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public void setFans(Long fans) {
        this.fans = fans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bilibili.friend
     *
     * @return the value of bilibili.friend
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public String getFriend() {
        return friend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bilibili.friend
     *
     * @param friend the value for bilibili.friend
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public void setFriend(String friend) {
        this.friend = friend == null ? null : friend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bilibili.sign
     *
     * @return the value of bilibili.sign
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bilibili.sign
     *
     * @param sign the value for bilibili.sign
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bilibili.vipType
     *
     * @return the value of bilibili.vipType
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public Integer getViptype() {
        return viptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bilibili.vipType
     *
     * @param viptype the value for bilibili.vipType
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public void setViptype(Integer viptype) {
        this.viptype = viptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bilibili.vipStatus
     *
     * @return the value of bilibili.vipStatus
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public Integer getVipstatus() {
        return vipstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bilibili.vipStatus
     *
     * @param vipstatus the value for bilibili.vipStatus
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public void setVipstatus(Integer vipstatus) {
        this.vipstatus = vipstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bilibili.archive_count
     *
     * @return the value of bilibili.archive_count
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public Long getArchiveCount() {
        return archiveCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bilibili.archive_count
     *
     * @param archiveCount the value for bilibili.archive_count
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public void setArchiveCount(Long archiveCount) {
        this.archiveCount = archiveCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bilibili.article_count
     *
     * @return the value of bilibili.article_count
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public Long getArticleCount() {
        return articleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bilibili.article_count
     *
     * @param articleCount the value for bilibili.article_count
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public void setArticleCount(Long articleCount) {
        this.articleCount = articleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bilibili.follower
     *
     * @return the value of bilibili.follower
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public Long getFollower() {
        return follower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bilibili.follower
     *
     * @param follower the value for bilibili.follower
     *
     * @mbg.generated Sat Feb 06 17:10:16 CST 2021
     */
    public void setFollower(Long follower) {
        this.follower = follower;
    }
}