package com.myLogger.dao.mapper;

public interface ErrorlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ErrorLog
     *
     * @mbg.generated Sat Feb 06 23:04:55 CST 2021
     */
    long countByExample(ErrorlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ErrorLog
     *
     * @mbg.generated Sat Feb 06 23:04:55 CST 2021
     */
    int deleteByPrimaryKey(Long mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ErrorLog
     *
     * @mbg.generated Sat Feb 06 23:04:55 CST 2021
     */
    int insert(Errorlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ErrorLog
     *
     * @mbg.generated Sat Feb 06 23:04:55 CST 2021
     */
    int insertSelective(Errorlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ErrorLog
     *
     * @mbg.generated Sat Feb 06 23:04:55 CST 2021
     */
    Errorlog selectByPrimaryKey(Long mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ErrorLog
     *
     * @mbg.generated Sat Feb 06 23:04:55 CST 2021
     */
    int updateByPrimaryKeySelective(Errorlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ErrorLog
     *
     * @mbg.generated Sat Feb 06 23:04:55 CST 2021
     */
    int updateByPrimaryKey(Errorlog record);
}